---
title: Planetary Solvency
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    kind: news
    link: ''
    source: ''
tagline: A systems approach to global risk management for human prosperity.
description: Planetary Solvency is a systems approach to understanding and managing
  global risk in support of long-term human prosperity.
url: https://test.planetarysolvency.org
baseurl: 
markdown: kramdown
permalink: "/news/:title/"
plugins:
- jekyll-sitemap
- jekyll-feed
sass:
  style: compressed
exclude:
- functions
- tests
- Gemfile
- Gemfile.lock
- README.md
- EDITING.md
- vendor
- node_modules
