---
title: Planetary Solvency
timezone: Europe/London
collections:
  intelligence-hub:
    title: Intelligence Hub
    output: true
    permalink: intel-hub
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: A systems approach to global risk management for human prosperity.
description: Planetary Solvency is a systems approach to understanding and managing
  global risk in support of long-term human prosperity.
url: https://test.planetarysolvency.org
baseurl: 
markdown: kramdown
permalink: "/:title/"
plugins:
- jekyll-sitemap
- jekyll-feed
sass:
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- README.md
- vendor
- node_modules
