#!/usr/bin/env node
// Builds report cover thumbnails from the cover images in _uploads/.
//
//   node scripts/process-covers.mjs [--force]
//
// Every cover is made the same shape (A4 portrait, 1 : 1.4142) so the report grid and the research list line up.
// For each file in _uploads/ it writes, to assets/images/covers/:
//   <id>-480.webp|jpg, <id>-240.webp|jpg
// The id is the filename without its extension, lower case and hyphenated. Covers that are slightly off A4 are
// trimmed from the bottom edge (the top, with the title, is always kept). Sizes larger than the original are skipped
// (no upscaling); a cover narrower than the largest size is also kept at its own width. Metadata is stripped and colour is sRGB.
// It then rewrites _data/cover_files.yml, listing the widths that exist for each id. Re-running only processes covers
// that are new or changed, or whose settings have changed. Use --force to redo everything.
//
// Needs ImageMagick 7 (`magick`) or 6 (`convert`) with WebP support. No npm packages.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const WIDTHS = [480, 240];
const RATIO = 1.4142;            // height / width (A4). Must match `cover_ratio` in _includes/report-cover.html.
const WEBP_QUALITY = 82;
const JPEG_QUALITY = 84;
const SOURCE_TYPES = new Set(['.png', '.jpg', '.jpeg', '.tif', '.tiff', '.webp']);

const root = resolve0();
const srcDir = join(root, '_uploads');
const outDir = join(root, 'assets', 'images', 'covers');
const manifestPath = join(root, '_data', 'cover_files.yml');
const settingsPath = join(outDir, '.process-settings.json');
const force = process.argv.includes('--force');

function resolve0() { return join(dirname(fileURLToPath(import.meta.url)), '..'); }
function fail(msg) { console.error(`process-covers: ${msg}`); process.exit(1); }
function run(cmd, args) { return execFileSync(cmd, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); }

let im;
for (const c of [{ convert: ['magick'], identify: ['magick', 'identify'] }, { convert: ['convert'], identify: ['identify'] }]) {
  try { run(c.convert[0], [...c.convert.slice(1), '-version']); im = c; break; } catch { /* try next */ }
}
if (!im) fail('ImageMagick not found. Install it from https://imagemagick.org and try again.');
const convert = (a) => run(im.convert[0], [...im.convert.slice(1), ...a]);
const identify = (f) => run(im.identify[0], [...im.identify.slice(1), '-format', '%w %h', `${f}[0]`]).trim().split(' ').map(Number);

const slug = (name) => name.toLowerCase().replace(/\.[^.]+$/, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
const settings = { widths: WIDTHS, ratio: RATIO, webp: WEBP_QUALITY, jpeg: JPEG_QUALITY };
let previous = {};
try { previous = JSON.parse(readFileSync(settingsPath, 'utf8')); } catch { /* first run */ }
const rebuild = force || JSON.stringify(previous) !== JSON.stringify(settings);

mkdirSync(outDir, { recursive: true });
const seen = new Map();
const manifest = {};
let written = 0;

for (const file of readdirSync(srcDir).sort()) {
  const src = join(srcDir, file);
  if (!statSync(src).isFile() || !SOURCE_TYPES.has(extname(file).toLowerCase())) continue;
  const id = slug(file);
  if (seen.has(id)) fail(`"${file}" and "${seen.get(id)}" both become "${id}". Rename one.`);
  seen.set(id, file);

  const [srcWidth] = identify(src);
  // Never upscale. A cover narrower than the largest size is also offered at its own width, so it is as sharp as it can be.
  const widths = WIDTHS.filter((w) => w <= srcWidth);
  if (srcWidth < WIDTHS[0]) widths.unshift(srcWidth);
  manifest[id] = widths;

  for (const w of widths) {
    const h = Math.round(w * RATIO);
    for (const [ext, quality] of [['webp', WEBP_QUALITY], ['jpg', JPEG_QUALITY]]) {
      const out = join(outDir, `${id}-${w}.${ext}`);
      if (!rebuild && existsSync(out) && statSync(out).mtimeMs >= statSync(src).mtimeMs) continue;
      convert([
        src, '-background', 'white', '-alpha', 'remove', '-alpha', 'off',
        '-colorspace', 'sRGB', '-filter', 'Lanczos', '-resize', `${w}x${h}^`,
        '-gravity', 'north', '-extent', `${w}x${h}`, '+repage', '-strip', '-quality', String(quality), out,
      ]);
      written++;
    }
  }
}

const yaml = ['# Generated by scripts/process-covers.mjs. Do not edit: the widths that exist for each cover.',
  ...Object.entries(manifest).map(([id, w]) => `${id}: [${w.join(', ')}]`)].join('\n') + '\n';
writeFileSync(manifestPath, yaml);
writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + '\n');
console.log(`${Object.keys(manifest).length} covers, ${written} files written.`);

// Remind about covers that no report uses, and reports that name a missing cover.
const reports = readFileSync(join(root, '_data', 'reports.yml'), 'utf8');
for (const m of reports.matchAll(/^\s*cover:\s*(\S+)/gm)) if (!manifest[m[1]]) console.warn(`WARNING: reports.yml uses cover "${m[1]}" but there is no file for it in _uploads/.`);
